/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import connectDB.ConnectDB;
import dao.NhanVien_DAO;
import dao.PhongBan_DAO;
import entity.NhanVien;
import entity.PhongBan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmEmployeeAdmin extends javax.swing.JPanel {

    private NhanVien_DAO nv_DAO;
    private PhongBan_DAO pb_DAO;
    private String isFlag = "";
    public frmEmployeeAdmin() {
        initComponents();
        KhoaMo(false);
        LayNguonSP();
    }
    public void xoatrang() {
        txt_MaNV.setText("");
        txt_TenNV.setText("");
        txt_Email.setText("");
        txt_SDT.setText("");
        txt_DiaChi.setText("");
        txt_Tuoi.setText("");
    }

    private void KhoaMo(boolean b) {
        txt_MaNV.setEditable(b);
        txt_TenNV.setEditable(b);
        txt_Email.setEditable(b);
        txt_SDT.setEditable(b);
        txt_DiaChi.setEnabled(b);
        cb_ChucVu.setEnabled(b);
        txt_Tuoi.setEditable(b);
        cb_PhongBan.setEditable(b);
        
        
        btnThem.setEnabled(!b);
        btnSua.setEnabled(!b);
        btnXoa.setEnabled(!b);

        btnLuu.setEnabled(b);
        btnHuy.setEnabled(b);

        tbl_QL_NhanVien.setEnabled(!b);
    }
    
    private boolean validation(){
        if (txt_MaNV.getText().isEmpty() && !txt_MaNV.getText().matches("^NV\\d+$")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã nhân viên.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if (txt_TenNV.getText().isEmpty() && !txt_TenNV.getText().matches("([A-Z]{1}[a-z])+")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhân viên.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if (txt_SDT.getText().isEmpty() && !txt_SDT.getText().matches("[0][0-9]{10}")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại nhân viên.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if (txt_DiaChi.getText().isEmpty() && !txt_DiaChi.getText().matches("[0-9a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ nhân viên.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txt_Tuoi.getText().isEmpty() && Integer.parseInt(txt_Tuoi.getText())<0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tuổi nhân viên.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txt_Email.getText().isEmpty() && !txt_Email.getText().matches("[A-Za-z0-9]+@[gmail.com]")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email nhân viên.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        return true;
    }
    private void LayNguonSP() {
        tbl_QL_NhanVien.removeAll();
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
                // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        nv_DAO = new NhanVien_DAO();
        List<NhanVien> listNV = nv_DAO.getAllTbNhanVien();
        if (tbl_QL_NhanVien.getModel() == null) {
            String[] arr = {"Mã NV", "Ten NV", "SDT", "Địa Chỉ", "Email", "Giới Tính", "Chức vụ", "Tuổi", "Mã Phòng Ban"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            tbl_QL_NhanVien.setModel(model);
        }
        DefaultTableModel model = (DefaultTableModel) tbl_QL_NhanVien.getModel();
        model.setRowCount(0);
        
        for(NhanVien nv: listNV) {
            model.addRow(new Object[] {nv.getMaNhanVien(),
                nv.getHoTen(), nv.getSdt(), nv.getDiaChi(),
                nv.getEmail(), nv.getGioiTinh()?"Nam":"Nu", nv.getChucVu(), 
                nv.getTuoi(),nv.getMaPhongBan().getMaPhongBan()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rad_nu = new javax.swing.JRadioButton();
        rad_nam = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_ChucVu = new javax.swing.JComboBox<>();
        cb_PhongBan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        txt_Tuoi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_timkiem = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_HienAll = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_QL_NhanVien = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        jLabel2.setText("Mã Nhân Viên:");

        jLabel3.setText("Tên Nhân Viên:");

        jLabel4.setText("Email:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel5.setText("Số điện thoại:");

        txt_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTActionPerformed(evt);
            }
        });

        jLabel6.setText("Giới Tính:");

        rad_nu.setText("Nữ");

        rad_nam.setSelected(true);
        rad_nam.setText("Nam");
        rad_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_namActionPerformed(evt);
            }
        });

        jLabel7.setText("Địa chỉ:");

        jLabel9.setText("Chức Vụ:");

        cb_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên Sửa Chữa", "Nhân Viên Bán Hàng", "Kế Toán", "Bảo Vệ", "Nhân Viên Marketing" }));
        cb_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ChucVuActionPerformed(evt);
            }
        });

        cb_PhongBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"PBKT","PBNS","PBTC" }));
        cb_PhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_PhongBanActionPerformed(evt);
            }
        });

        jLabel10.setText("Phòng Ban:");

        txt_DiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiaChiActionPerformed(evt);
            }
        });

        txt_Tuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TuoiActionPerformed(evt);
            }
        });

        jLabel11.setText("Tuổi:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaNV)
                    .addComponent(txt_TenNV)
                    .addComponent(txt_Email)
                    .addComponent(txt_SDT)
                    .addComponent(txt_DiaChi)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(rad_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rad_nu))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cb_PhongBan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_ChucVu, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)))
                        .addGap(0, 222, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(rad_nu)
                    .addComponent(rad_nam))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cb_PhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 180, 209));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        btnLuu.setText("     Lưu");
        btnLuu.setToolTipText("");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/del.png"))); // NOI18N
        btnXoa.setText("     Xóa");
        btnXoa.setToolTipText("");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        btnHuy.setText("     Hủy");
        btnHuy.setToolTipText("");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-icon.png"))); // NOI18N
        btnThem.setText("  Thêm");
        btnThem.setToolTipText("");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit (1).png"))); // NOI18N
        btnSua.setText("    Sửa");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chức năng", jPanel6);

        jPanel5.setBackground(new java.awt.Color(153, 180, 209));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/system_search.png"))); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Tìm Theo Mã Nhân Viên:");

        btn_HienAll.setText("Hiện Tất Cả");
        btn_HienAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HienAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_timkiem)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_HienAll, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_HienAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm", jPanel5);

        tbl_QL_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Số điện thoại", "Địa chỉ", "Email", "Giới tính", "Chức vụ", "Tuổi", "Mã phòng ban"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_QL_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_QL_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_QL_NhanVien);

        jPanel7.setBackground(new java.awt.Color(153, 180, 209));

        jLabel1.setBackground(new java.awt.Color(153, 180, 209));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            ConnectDB.getInstance().connect();
        } catch (SQLException e) {
                // TODO Auto-generated catch block
            e.printStackTrace();
        }
        boolean b= true;
        txt_MaNV.setEditable(b);
        txt_TenNV.setEditable(b);
        txt_Email.setEditable(b);
        txt_SDT.setEditable(b);
        txt_DiaChi.setEnabled(b);
        cb_ChucVu.setEnabled(b);
        txt_Tuoi.setEditable(b);
        cb_PhongBan.setEditable(b);
        
        
        btnThem.setEnabled(b);
        btnSua.setEnabled(b);
        btnXoa.setEnabled(b);

        btnLuu.setEnabled(!b);
        btnHuy.setEnabled(!b);
        
        nv_DAO = new NhanVien_DAO();
        if (tbl_QL_NhanVien.getSelectedRow() >= 0) {
            int row = tbl_QL_NhanVien.getSelectedRow();
            String ma = txt_MaNV.getText();
            NhanVien nv = new NhanVien(ma);
            try {
                nv_DAO.delete(nv);
                DefaultTableModel model = (DefaultTableModel) tbl_QL_NhanVien.getModel();
                model.removeRow(row);
            } catch (Exception e1) {
                JOptionPane.showMessageDialog(this, "Not delete");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xóa.");
        }
        xoatrang();
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        KhoaMo(false);
        txt_MaNV.setEnabled(true);
        xoatrang();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        isFlag = "them";
        xoatrang();
        KhoaMo(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        isFlag = "update";
        KhoaMo(true);
        txt_MaNV.setEditable(false);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        if (txt_timkiem.getText().equals("")) {
            LayNguonSP();
        }
        try {
            ConnectDB.getInstance().connect();
            String timkiem = txt_timkiem.getText();

            // Xóa toàn bộ dữ liệu trong tbl_QL_NhanVien
            DefaultTableModel model = (DefaultTableModel) tbl_QL_NhanVien.getModel();
            model.setRowCount(0);

            nv_DAO = new NhanVien_DAO();
            ArrayList<NhanVien> listNV = nv_DAO.getNVTheoMa(timkiem);

            if (model.getColumnCount() == 0) {
                String[] arr = {"Mã NV", "Ten NV", "SDT", "Địa Chỉ", "Email", "Giới Tính", "Chức vụ", "Tuổi", "Mã Phòng Ban"};
                model.setColumnIdentifiers(arr);
            }
            for(NhanVien nv: listNV) {
                model.addRow(new Object[] {nv.getMaNhanVien(),
                    nv.getHoTen(), nv.getSdt(), nv.getDiaChi(),
                    nv.getEmail(), nv.getGioiTinh()?"Nam":"Nu", nv.getChucVu(), 
                    nv.getTuoi(),nv.getMaPhongBan().getMaPhongBan()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_HienAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HienAllActionPerformed
        LayNguonSP();
    }//GEN-LAST:event_btn_HienAllActionPerformed
//String[] arr = {"Mã NV", "Ten NV", "SDT", "Địa Chỉ", "Email", "Giới Tính", "Chức vụ", "Tuổi", "Mã Phòng Ban"};
    private void tbl_QL_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_QL_NhanVienMouseClicked
        int row = tbl_QL_NhanVien.getSelectedRow();
        if (row >= 0) {
            txt_MaNV.setText(tbl_QL_NhanVien.getValueAt(row, 0).toString());
            txt_TenNV.setText(tbl_QL_NhanVien.getValueAt(row, 1).toString());
            txt_SDT.setText(tbl_QL_NhanVien.getValueAt(row, 2).toString());
            txt_DiaChi.setText(tbl_QL_NhanVien.getValueAt(row, 3).toString());
            txt_Email.setText(tbl_QL_NhanVien.getValueAt(row, 4).toString());
            String sex;
            sex = tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(),5).toString();
            if (sex.equals("Nam")) {
                rad_nam.setSelected(true);
                rad_nu.setSelected(false);
            } else if (sex.equals("Nữ")) {
                rad_nam.setSelected(false);
                rad_nu.setSelected(true);
            }
            cb_ChucVu.setSelectedItem(tbl_QL_NhanVien.getValueAt(row, 6).toString());
            txt_Tuoi.setText(tbl_QL_NhanVien.getValueAt(row, 7).toString());
            cb_PhongBan.setSelectedItem(tbl_QL_NhanVien.getValueAt(row, 8).toString());

        }
    }//GEN-LAST:event_tbl_QL_NhanVienMouseClicked

    private void rad_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_namActionPerformed

    private void txt_DiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DiaChiActionPerformed

    private void txt_TuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TuoiActionPerformed

    private void cb_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ChucVuActionPerformed

    private void cb_PhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_PhongBanActionPerformed
    }//GEN-LAST:event_cb_PhongBanActionPerformed

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        if(isFlag.equalsIgnoreCase("update")){
            try 
            {
                ConnectDB.getInstance().connect();
            } catch (SQLException e) {
                    // TODO Auto-generated catch block
                e.printStackTrace();
            }
            nv_DAO = new NhanVien_DAO();
            int rowChoice = tbl_QL_NhanVien.getSelectedRow(); 
            
            
            String maNhanVien = txt_MaNV.getText();
            
            
            if(validation() == true){
            
                String hoTen = txt_TenNV.getText();
                String sdt = txt_SDT.getText();

                String diaChi = txt_DiaChi.getText();
                String email = txt_Email.getText();
                boolean phai = rad_nam.isSelected();
                String chucVu = cb_ChucVu.getSelectedItem().toString();
                int tuoi = Integer.parseInt(txt_Tuoi.getText());
                String phongBan = cb_PhongBan.getSelectedItem().toString();

                PhongBan phban = new PhongBan(phongBan);
                NhanVien nv = new NhanVien(maNhanVien, hoTen, sdt,diaChi, email, phai,chucVu,tuoi, phban);
                try {
                    nv_DAO.update(nv);
                    if (tbl_QL_NhanVien.getModel() == null) {
                        String[] arr = {"Mã NV", "Ten NV", "SDT", "Địa Chỉ", "Email", "Giới Tính", "Chức vụ", "Tuổi", "Mã Phòng Ban"};
                        DefaultTableModel model = new DefaultTableModel(arr, 0);
                        tbl_QL_NhanVien.setModel(model);
                    }
                    DefaultTableModel model = (DefaultTableModel) tbl_QL_NhanVien.getModel();

                    model.setValueAt(maNhanVien, rowChoice, 0);
                    model.setValueAt(hoTen, rowChoice, 1);
                    model.setValueAt(sdt, rowChoice, 2);
                    model.setValueAt(diaChi, rowChoice, 3);
                    model.setValueAt(email, rowChoice, 4);
                    model.setValueAt(phai?"Nam":"Nu", rowChoice, 5);
                    model.setValueAt(chucVu, rowChoice, 6);
                    model.setValueAt(tuoi, rowChoice, 7);
                    model.setValueAt(phongBan, rowChoice, 8);

                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(this, "Fail");
                }
                isFlag = "";
                KhoaMo(false);
            }
        }
        else{
            try {
                ConnectDB.getInstance().connect();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            nv_DAO = new NhanVien_DAO();
            if(validation()==true){
            
                String maNhanVien = txt_MaNV.getText();
                String hoTen = txt_TenNV.getText();
                String sdt = txt_SDT.getText();
                String diaChi = txt_DiaChi.getText();
                String email = txt_Email.getText();
                boolean phai = rad_nam.isSelected();
                int tuoi = Integer.parseInt(txt_Tuoi.getText());
                String chucVu = cb_ChucVu.getSelectedItem().toString();
                String phongBan = cb_PhongBan.getSelectedItem().toString();

                PhongBan phban = new PhongBan(phongBan);
                NhanVien nv = new NhanVien(maNhanVien, hoTen, sdt,diaChi, email, phai, chucVu , tuoi, phban);



                try {
                    nv_DAO.create(nv);
                    if (tbl_QL_NhanVien.getModel() == null) {
                        String[] arr = {"Mã NV", "Ten NV", "SDT", "Địa Chỉ", "Email", "Giới Tính", "Chức vụ", "Tuổi", "Mã Phòng Ban"};
                        DefaultTableModel model = new DefaultTableModel(arr, 0);
                        tbl_QL_NhanVien.setModel(model);
                    }
                    DefaultTableModel model = (DefaultTableModel) tbl_QL_NhanVien.getModel();

                    model.addRow(new Object[] { nv.getMaNhanVien(),
                                        nv.getHoTen(), nv.getSdt(), nv.getDiaChi(),
                                        nv.getEmail(), nv.getGioiTinh()?"Nam":"Nu" , nv.getChucVu() ,nv.getTuoi(), nv.getMaPhongBan().getMaPhongBan()});
                } catch (Exception e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Trùng");
                }
                isFlag = "";
                KhoaMo(false);
            }
        }
    }//GEN-LAST:event_btnLuuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_HienAll;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cb_ChucVu;
    private javax.swing.JComboBox<String> cb_PhongBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rad_nam;
    private javax.swing.JRadioButton rad_nu;
    private javax.swing.JTable tbl_QL_NhanVien;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_Tuoi;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    
}
