/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import connectDB.ConnectDB;
import java.awt.Image;
import java.io.File;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.serial.SerialBlob;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmEmployee extends javax.swing.JPanel {

    /**
     * Creates new form frmEmployee
     */
    private frmAdminMenu parent_Form;
    String timkiem = "";
    boolean ktThem;
    String macu;
    String sql;
    DefaultTableModel btn = new DefaultTableModel();
    private byte[] anh;
    public frmEmployee() {
        initComponents();
        KhoaMo(false);
        LayNguonSP();
    }
    public void xoatrang() {
        txt_MaNV.setText("");
        txt_TenNV.setText("");
        txt_Email.setText("");
        txt_SDT.setText("");
        txt_DiaChi.setText("");
    }

    private void KhoaMo(boolean b) {
        txt_MaNV.setEditable(b);
        txt_TenNV.setEditable(b);
        txt_Email.setEditable(b);
        txt_SDT.setEditable(b);
        txt_DiaChi.setEnabled(b);
        cb_ChucVu.setEnabled(b);

        btnThem.setEnabled(!b);
        btnSua.setEnabled(!b);
        btnXoa.setEnabled(!b);

        btnLuu.setEnabled(b);
        btnHuy.setEnabled(b);

        tbl_QL_NhanVien.setEnabled(!b);
    }

    private void LayNguonSP() {
        try {
            tbl_QL_NhanVien.removeAll();
            String[] arr = {"Mã NV", "Tên NV", "Email", "SDT", "Chức Vụ", "Giới Tính", "Địa Chỉ", "Hình"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);

            Connection connection = ConnectDB.getConnection();
            String query = "SELECT * FROM TT_NhanVien";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MaNV"));
                vector.add(rs.getString("TenNV"));
                vector.add(rs.getString("Email"));
                vector.add(rs.getString("SDT"));
                vector.add(rs.getString("ChucVu"));
                vector.add(rs.getString("GioiTinh"));
                vector.add(rs.getString("DiaChi"));
                vector.add(rs.getString("Hinh"));

                model.addRow(vector);
            }
            tbl_QL_NhanVien.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(frmEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public boolean ktTrungThem() throws ClassNotFoundException, SQLException {
        int row = 0;
        Connection conn = ConnectDB.getConnection();
        sql = "Select * from TT_NhanVien where MaNV = N'" + txt_MaNV.getText() + "'";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            row++;
        }
        if (row > 0) { //ktra có dữ liệu k
            return true;
        } else {
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        parentform = new javax.swing.JPanel();
        imaImage = new javax.swing.JLabel();
        btn_MoHinhAnh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdb_nu = new javax.swing.JRadioButton();
        rdb_nam = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DiaChi = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        cb_ChucVu = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_timkiem = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_HienAll = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_QL_NhanVien = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        parentform.setBorder(javax.swing.BorderFactory.createTitledBorder("Ảnh"));

        imaImage.setBackground(new java.awt.Color(102, 102, 255));
        imaImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        imaImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imaImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anh_the.png"))); // NOI18N

        btn_MoHinhAnh.setText("Mở Hình");
        btn_MoHinhAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MoHinhAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parentformLayout = new javax.swing.GroupLayout(parentform);
        parentform.setLayout(parentformLayout);
        parentformLayout.setHorizontalGroup(
            parentformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imaImage, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
            .addGroup(parentformLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btn_MoHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parentformLayout.setVerticalGroup(
            parentformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentformLayout.createSequentialGroup()
                .addComponent(imaImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MoHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Tên Nhân Viên");

        jLabel4.setText("Email:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel5.setText("Số điện thoại");

        txt_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTActionPerformed(evt);
            }
        });

        jLabel6.setText("Giới Tính");

        rdb_nu.setText("Nữ");

        rdb_nam.setSelected(true);
        rdb_nam.setText("Nam");
        rdb_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_namActionPerformed(evt);
            }
        });

        jLabel7.setText("Địa chỉ");

        txt_DiaChi.setColumns(20);
        txt_DiaChi.setRows(5);
        jScrollPane1.setViewportView(txt_DiaChi);

        jLabel9.setText("Chức Vụ:");

        cb_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên Sửa Chữa", "Nhân Viên Bán Hàng", "Kế Toán", "Bảo Vệ", "Nhân Viên Marketing" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_TenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(txt_MaNV)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Email)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(rdb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rdb_nu))
                                        .addComponent(cb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdb_nam)
                            .addComponent(rdb_nu)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        jPanel6.setBackground(new java.awt.Color(153, 180, 209));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        btnLuu.setText("     Lưu");
        btnLuu.setToolTipText("");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/del.png"))); // NOI18N
        btnXoa.setText("     Xóa");
        btnXoa.setToolTipText("");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        btnHuy.setText("     Hủy");
        btnHuy.setToolTipText("");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-icon.png"))); // NOI18N
        btnThem.setText("  Thêm");
        btnThem.setToolTipText("");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit (1).png"))); // NOI18N
        btnSua.setText("    Sửa");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chức năng", jPanel6);

        jPanel5.setBackground(new java.awt.Color(153, 180, 209));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/system_search.png"))); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Tìm Theo Tên SP");

        btn_HienAll.setText("Hiện Tất Cả");
        btn_HienAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HienAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_timkiem)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_HienAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btn_HienAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Tìm kiếm", jPanel5);

        tbl_QL_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Email", "SDT", "Chức Vụ", "Giới Tính", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_QL_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_QL_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_QL_NhanVien);

        jPanel7.setBackground(new java.awt.Color(153, 180, 209));

        jLabel1.setBackground(new java.awt.Color(153, 180, 209));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parentform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(parentform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1189, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MoHinhAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MoHinhAnhActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".png");
                }
            }

            @Override
            public String getDescription() {
                return "Image File (*.png)";
            }
        });
        if (chooser.showOpenDialog(parent_Form) == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = imagehelper.resize(icon.getImage(), 305, 230);
            ImageIcon resizedIcon = new ImageIcon(img);
            imaImage.setIcon(resizedIcon);
            anh = imagehelper.toByteArray(img, "png");
        } catch (Exception e) {
            e.printStackTrace();
            messagedialoghelper.showErrorDialog(parentform, e.getMessage(), "loi");
        }
    }//GEN-LAST:event_btn_MoHinhAnhActionPerformed

    private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txt_MaNV.getText().equals("") || txt_TenNV.getText().equals("") || txt_Email.getText().equals("") || txt_SDT.getText().equals("") || txt_DiaChi.getText().equals("")) {
            sb.append("không Được Để Nội Dung Các ô Trống");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
            return;
        }

        if (ktThem == true) {
            try {
                if (ktTrungThem() == true) {
                    JOptionPane.showMessageDialog(null, "Trùng mã NV: " + txt_MaNV.getText() + " !"/*, "Error", JOptionPane.ERROR_MESSAGE*/);
                    return;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        try {
            Connection conn = ConnectDB.getConnection();
            if (ktThem == true) {  // --------------insert
                String sql = "INSERT INTO TT_NhanVien (MaNV, TenNV, Email, SDT, ChucVu, GioiTinh, DiaChi, Hinh) values(?,?,?,?,?,?,?,?)";
                try {
                    Connection con = ConnectDB.getConnection();
                    PreparedStatement pstmt = con.prepareStatement(sql);

                    pstmt.setString(1, txt_MaNV.getText());
                    pstmt.setString(2, txt_TenNV.getText());
                    pstmt.setString(3, txt_Email.getText());
                    pstmt.setString(4, txt_SDT.getText());
                    pstmt.setString(5, cb_ChucVu.getSelectedItem().toString());
                    String a = "";
                    if (rdb_nam.isSelected()) {
                        a = "Nam";
                    } else if (rdb_nu.isSelected()) {
                        a = "Nữ";
                    }
                    pstmt.setString(6, a);
                    pstmt.setString(7, txt_DiaChi.getText());
                    Blob hinh = new SerialBlob(anh);
                    pstmt.setBlob(8, hinh);
                    pstmt.executeUpdate();
                    ConnectDB.closeConnection(conn);
                } catch (Exception e) {
                }
            } else {
                String sql = "update TT_NhanVien set TenNV=?,Email=?,SDT=?,ChucVu=?,GioiTinh=?,DiaChi=?,Hinh=? where MaNV=?";
                try {
                    Connection con = ConnectDB.getConnection();
                    PreparedStatement pstmt = con.prepareStatement(sql);

                    pstmt.setString(8, txt_MaNV.getText());
                    pstmt.setString(1, txt_TenNV.getText());
                    pstmt.setString(2, txt_Email.getText());
                    pstmt.setString(3, txt_SDT.getText());
                    pstmt.setString(4, cb_ChucVu.getSelectedItem().toString());
                    if (rdb_nam.isSelected()) {
                        pstmt.setString(5, "Nam");
                    } else {
                        pstmt.setString(5, "Nữ");
                    }
                    pstmt.setString(6, txt_DiaChi.getText());
                    Blob hinh = new SerialBlob(anh);
                    pstmt.setBlob(7, hinh);

                    pstmt.executeUpdate();
                    ConnectDB.closeConnection(conn);
                } catch (Exception e) {
                }
            }

            if (ktThem == true) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Sửa thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        KhoaMo(false);
        LayNguonSP();
        txt_MaNV.setEditable(false);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txt_MaNV.getText().equals("") && txt_TenNV.getText().equals("")) {
            return;
        }
        int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không?");
        if (result == 0) {
            int position = tbl_QL_NhanVien.getSelectedRow();
            String data = tbl_QL_NhanVien.getModel().getValueAt(position, 0).toString();
            System.out.println(data);
            try {
                Connection connection = ConnectDB.getConnection();
                String query = " DELETE FROM TT_NhanVien WHERE MaNV = ? ";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1, data);
                ps.executeUpdate();

                ConnectDB.closeConnection(connection);
                JOptionPane.showMessageDialog(null, "Xóa thành công");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        xoatrang();
        LayNguonSP();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        KhoaMo(false);
        txt_MaNV.setEnabled(true);
        xoatrang();
        if (tbl_QL_NhanVien.getSelectedRow() >= 0) {
            txt_MaNV.setText(tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 0) + "");
            txt_TenNV.setText(tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 1) + "");
            txt_Email.setText(tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 2) + "");
            txt_SDT.setText(tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 3) + "");
            cb_ChucVu.setSelectedItem(tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 4));
            String sex = tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 5).toString();
            if (sex.equals("Nam")) {
                rdb_nam.setSelected(true);
            } else if (sex.equals("Nữ")) {
                rdb_nu.setSelected(true);
            }
            txt_DiaChi.setText(tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 6) + "");
            String masv = tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 0).toString();
            try {
                int number;
                Connection connection = ConnectDB.getConnection();
                String sql = "select * from TT_NhanVien where MaNV= '" + masv + "'";
                Statement ps = connection.createStatement();
                ResultSet rs = ps.executeQuery(sql);
                if (rs.next()) {

                }
                Blob blob = rs.getBlob("Hinh");
                if (blob != null) {
                    anh = blob.getBytes(1, (int) blob.length());
                    Image img = imagehelper.createImageFromByteArray(anh, "jpg");
                    imaImage.setIcon(new ImageIcon(img));
                } else {
                    imaImage.setIcon(new ImageIcon(getClass().getResource("")));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        xoatrang();
        KhoaMo(true);
        ktThem = true;
        anh = null;
        ImageIcon icon = new ImageIcon(
            getClass().getResource("/Images/anh_mau.png"));
        imaImage.setIcon(icon);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txt_MaNV.getText().equals("") && txt_TenNV.getText().equals("")) {
            return;
        }
        KhoaMo(true);
        ktThem = false;
        macu = txt_MaNV.getText();
        txt_MaNV.setEnabled(false);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        if (txt_timkiem.getText().equals("")) {
            LayNguonSP();
        }
        try {
            timkiem = txt_timkiem.getText();
            tbl_QL_NhanVien.removeAll();
            String[] arr = {"Mã NV", "Tên NV", "Email", "SDT", "Chức Vụ", "Giới Tính", "Địa Chỉ", "Hình"};
            DefaultTableModel model = new DefaultTableModel(arr, 0); //tạo TableModel chứa dữ liệu cho Jtable
            String sql = "select * from TT_NhanVien where TenNV like N'%" + timkiem + "%'";

            Connection connection = ConnectDB.getConnection();
            PreparedStatement ps = connection.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            // hiển thị dữ liệu lên jtable
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MaNV"));
                vector.add(rs.getString("TenNV"));
                vector.add(rs.getString("Email"));
                vector.add(rs.getString("SDT"));
                vector.add(rs.getString("ChucVu"));
                vector.add(rs.getString("GioiTinh"));
                vector.add(rs.getString("DiaChi"));
                vector.add(rs.getString("Hinh"));

                model.addRow(vector);
            }
            tbl_QL_NhanVien.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_HienAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HienAllActionPerformed
        LayNguonSP();
    }//GEN-LAST:event_btn_HienAllActionPerformed

    private void tbl_QL_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_QL_NhanVienMouseClicked
        int row = tbl_QL_NhanVien.getSelectedRow();
        if (row >= 0) {
            txt_MaNV.setText(tbl_QL_NhanVien.getValueAt(row, 0).toString());
            txt_TenNV.setText(tbl_QL_NhanVien.getValueAt(row, 1).toString());
            txt_Email.setText(tbl_QL_NhanVien.getValueAt(row, 2).toString());
            txt_SDT.setText(tbl_QL_NhanVien.getValueAt(row, 3).toString());
            cb_ChucVu.setSelectedItem(tbl_QL_NhanVien.getValueAt(row, 4).toString());
            String sex = tbl_QL_NhanVien.getValueAt(tbl_QL_NhanVien.getSelectedRow(), 5).toString();
            if (sex.equals("Nam")) {
                rdb_nam.setSelected(true);
            } else if (sex.equals("Nữ")) {
                rdb_nu.setSelected(true);
            }
            txt_DiaChi.setText(tbl_QL_NhanVien.getValueAt(row, 6).toString());

            String masv = tbl_QL_NhanVien.getValueAt(row, 0).toString();
            try {
                int number;
                Connection connection = ConnectDB.getConnection();
                String sql = "select * from TT_NhanVien where MaNV = '" + masv + "'";
                Statement ps = connection.createStatement();
                ResultSet rs = ps.executeQuery(sql);
                if (rs.next()) {

                }
                Blob blob = rs.getBlob("Hinh");
                if (blob != null) {
                    anh = blob.getBytes(1, (int) blob.length());
                    Image img = imagehelper.createImageFromByteArray(anh, "jpg");
                    imaImage.setIcon(new ImageIcon(img));
                } else {
                    imaImage.setIcon(new ImageIcon(getClass().getResource("")));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tbl_QL_NhanVienMouseClicked

    private void rdb_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_namActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_HienAll;
    private javax.swing.JButton btn_MoHinhAnh;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cb_ChucVu;
    private javax.swing.JLabel imaImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel parentform;
    private javax.swing.JRadioButton rdb_nam;
    private javax.swing.JRadioButton rdb_nu;
    private javax.swing.JTable tbl_QL_NhanVien;
    private javax.swing.JTextArea txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
