/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import connectDB.ConnectDB;
import dao.LoaiXe_DAO;
import dao.NhaPhanPhoi_DAO;
import dao.SanPham_DAO;
import entity.LoaiXe;
import entity.NhaPhanPhoi;
import entity.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADMIN
 */
public class frmMotoAdmin extends javax.swing.JPanel {

    /**
     * Creates new form frmMoto
     */
    private SanPham_DAO sp_DAO;
    private NhaPhanPhoi_DAO npp_DAO;
    private LoaiXe_DAO lx_DAO;
    private String isFlag = "";
    
    
    public frmMotoAdmin() {
        initComponents();
        KhoaMo(false);
        LayNguonSP();
    }
    public void xoatrang() {
        txtMaSP.setText("");
        txtTenSp.setText("");
        txtSoLuong.setText("");
        txtNamSX.setText("");
        txtGiaBan.setText("");
    }

    private void KhoaMo(boolean b) {
        txtMaSP.setEditable(b);
        txtTenSp.setEditable(b);
        txtNamSX.setEditable(b);
        txtGiaBan.setEditable(b);
        txtSoLuong.setEditable(b);
        cb_LoaiXe.setEnabled(b);
        cbNhaCC.setEnabled(b);
        cbMauSac.setEnabled(b);
        cbXiLanh.setEnabled(b);

        btnThem.setEnabled(!b);
        btnSua.setEnabled(!b);
        btnXoa.setEnabled(!b);

        btnLuu.setEnabled(b);
        btnHuy.setEnabled(b);

        tblSanPham.setEnabled(!b);
    }
    
     private boolean validation(){
        if (txtMaSP.getText().isEmpty() && !txtMaSP.getText().matches("^SP\\d+$")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã sản phẩm.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if (txtTenSp.getText().isEmpty() && !txtTenSp.getText().matches("([A-Z]{1}[a-z])+")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sản phẩm.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        if (txtNamSX.getText().isEmpty() && Integer.parseInt(txtNamSX.getText()) < 1990) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập năm sản xuất.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtGiaBan.getText().isEmpty() && Integer.parseInt(txtGiaBan.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtSoLuong.getText().isEmpty() && Integer.parseInt(txtSoLuong.getText())<0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng.", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        return true;
    }
    private void LayNguonSP() {
        tblSanPham.removeAll();
        try {
            ConnectDB.getInstance().connect();
        } catch (Exception e) {
                // TODO Auto-generated catch block
            e.printStackTrace();
        }
        sp_DAO = new SanPham_DAO();
        List<SanPham> listSP  = sp_DAO.getAllTableSanPham();
        
        if (tblSanPham.getModel() == null) {
            String[] arr = {"Mã SP", "Tên SP", "Loại Xe", "Nhà CC", "Giá Bán", "Năm SX", "Số Lượng" ,"Xi lanh", "Màu Sắc"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            tblSanPham.setModel(model);
        }
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        for(SanPham sp: listSP) {
            model.addRow(new Object[] {sp.getMaSanPham(),
                sp.getTenXe(), sp.getMaLoai().getMaLoai(),
                sp.getNhaPhanPhoi().getMaNhaPhanPhoi(), sp.getGia(), sp.getNamSanXuat() , sp.getSoLuong(),
                sp.getXiLanh(),sp.getMauSac()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenSp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb_LoaiXe = new javax.swing.JComboBox<>();
        cbNhaCC = new javax.swing.JComboBox<>(new String[] { "YAMAHA_VN", "HONDA_VN", "SUZUKI_VN"});
        txtNamSX = new javax.swing.JTextField();
        cbMauSac = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbXiLanh = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        btn_timkiem = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_HienAll = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1189, 699));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Sản Phẩm"));

        jLabel2.setText("Mã Sản Phẩm:");

        jLabel3.setText("Tên Sản Phẩm:");

        jLabel4.setText("Loại Xe:");

        jLabel5.setText("Nhà Cung Cấp:");

        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });

        jLabel6.setText("Giá Bán: ");

        jLabel7.setText("Năm Sản Xuất:");

        cb_LoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XEGA", "XEGON", "XESO"}));
        cb_LoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_LoaiXeActionPerformed(evt);
            }
        });

        cbNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhaCCActionPerformed(evt);
            }
        });

        cbMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vàng", "cam", "Tím", "nâu đậm", "đen", "trắng", "xám", "xanh nước biển", "xanh lá cây", "đỏ", "đỏ đen" }));

        jLabel9.setText("Màu Sắc:");

        cbXiLanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">50cc", "51cc-174cc", "175cc-400cc", "401cc-750cc", "751cc-1000cc","1000cc<" }));

        jLabel10.setText("Xi-lanh:");

        jLabel12.setText("Số lượng:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(84, 84, 84)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbXiLanh, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMaSP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamSX, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_LoaiXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(cbNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbXiLanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 180, 209));

        jLabel1.setBackground(new java.awt.Color(153, 180, 209));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản Lý Sản Phẩm");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 180, 209));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/system_search.png"))); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Tìm Theo Tên SP");

        btn_HienAll.setText("Hiện Tất Cả");
        btn_HienAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HienAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_timkiem)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_timkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_HienAll, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(80, 80, 80))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_HienAll, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tìm kiếm", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 180, 209));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-icon.png"))); // NOI18N
        btnThem.setText("    Thêm");
        btnThem.setToolTipText("");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        btnLuu.setText("     Lưu");
        btnLuu.setToolTipText("");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit (1).png"))); // NOI18N
        btnSua.setText("     Sửa");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/del.png"))); // NOI18N
        btnXoa.setText("     Xóa");
        btnXoa.setToolTipText("");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        btnHuy.setText("     Hủy");
        btnHuy.setToolTipText("");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chức năng", jPanel6);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Loại Xe", "Nhà Cung Cấp", "Giá Bán", "Năm SX", "Số lượng", "Xi-lanh", "Màu sắc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int row = tblSanPham.getSelectedRow();
        if (row >= 0) {
            txtMaSP.setText(tblSanPham.getValueAt(row, 0).toString());
            txtTenSp.setText(tblSanPham.getValueAt(row, 1).toString());
            cb_LoaiXe.setSelectedItem(tblSanPham.getValueAt(row, 2).toString());
            cbNhaCC.setSelectedItem(tblSanPham.getValueAt(row, 3).toString());
            txtGiaBan.setText(tblSanPham.getValueAt(row, 4).toString());
            txtNamSX.setText(tblSanPham.getValueAt(row, 5).toString());
            txtSoLuong.setText(tblSanPham.getValueAt(row, 6).toString());
            cbXiLanh.setSelectedItem(tblSanPham.getValueAt(row, 7).toString());
            cbMauSac.setSelectedItem(tblSanPham.getValueAt(row, 8).toString());
            
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        isFlag = "them";
        xoatrang();
        KhoaMo(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(isFlag.equals("them")){
            try {
                ConnectDB.getInstance().connect();
            } catch (Exception e) {
                e.printStackTrace();
            }
            sp_DAO = new SanPham_DAO();
            if(validation()==true){
                String MaSP = txtMaSP.getText();
                String TenSp = txtTenSp.getText();
                String Loaixe = cb_LoaiXe.getSelectedItem().toString();
                String NhaCC = cbNhaCC.getSelectedItem().toString();
                double GiaBan = Double.parseDouble(txtGiaBan.getText());
                int NamSX = Integer.parseInt(txtNamSX.getText());
                int SoLuong = Integer.parseInt(txtSoLuong.getText());
                String Xilanh = cbXiLanh.getSelectedItem().toString();
                String Mausac = cbMauSac.getSelectedItem().toString();


                LoaiXe LoaiXe = new LoaiXe(Loaixe);
                NhaPhanPhoi NPP = new NhaPhanPhoi(NhaCC);

                SanPham sp = new SanPham(MaSP, TenSp, LoaiXe, NPP , GiaBan, NamSX, SoLuong, Xilanh, Mausac);
                try {
                    sp_DAO.create(sp);
                    tblSanPham.removeAll();
                    if (tblSanPham.getModel() == null) {
                        String[] arr = {"Mã SP", "Tên SP", "Loại Xe", "Nhà CC", "Giá Bán", "Năm SX", "Số Lượng" ,"Xi lanh", "Màu Sắc"};
                        DefaultTableModel model = new DefaultTableModel(arr, 0);
                        tblSanPham.setModel(model);
                    }
                    DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
                    model.addRow(new Object[] {sp.getMaSanPham(),
                                    sp.getTenXe(), sp.getMaLoai().getMaLoai(),
                                    sp.getNhaPhanPhoi().getMaNhaPhanPhoi(), sp.getNamSanXuat() , sp.getGia(), sp.getSoLuong(),
                                    sp.getXiLanh(),sp.getMauSac()}
                    );
                } catch (Exception e1) {
                        e1.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Trùng");
                }

                isFlag = "";
                KhoaMo(false);
            }
        }else{
            try {
                ConnectDB.getInstance().connect();
            } catch (Exception e) {
                    // TODO Auto-generated catch block
                e.printStackTrace();
            }
            sp_DAO = new SanPham_DAO();
            int rowChoice = tblSanPham.getSelectedRow(); 
            
            String maSanPham = txtMaSP.getText();
            
            if(validation() == true){
            
                String MaSP = txtMaSP.getText();
                String TenSp = txtTenSp.getText();
                String Loaixe = cb_LoaiXe.getSelectedItem().toString();
                String NhaCC = cbNhaCC.getSelectedItem().toString();
                double GiaBan = Double.parseDouble(txtGiaBan.getText());
                int NamSX = Integer.parseInt(txtNamSX.getText());
                int SoLuong = Integer.parseInt(txtSoLuong.getText());
                String Xilanh = cbXiLanh.getSelectedItem().toString();
                String Mausac = cbMauSac.getSelectedItem().toString();


                LoaiXe LoaiXe = new LoaiXe(Loaixe);
                NhaPhanPhoi NPP = new NhaPhanPhoi(NhaCC);

                SanPham sp = new SanPham(MaSP, TenSp, LoaiXe, NPP , GiaBan, NamSX, SoLuong, Xilanh, Mausac);
                try {
                    sp_DAO.update(sp);
                    if (tblSanPham.getModel() == null) {
                        String[] arr = {"Mã SP", "Tên SP", "Loại Xe", "Nhà CC", "Giá Bán", "Năm SX", "Số Lượng" ,"Xi lanh", "Màu Sắc"};
                        DefaultTableModel model = new DefaultTableModel(arr, 0);
                        tblSanPham.setModel(model);
                    }
                    DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();

                    model.setValueAt(MaSP, rowChoice, 0);
                    model.setValueAt(TenSp, rowChoice, 1);
                    model.setValueAt(Loaixe, rowChoice, 2);
                    model.setValueAt(NhaCC, rowChoice, 3);
                    model.setValueAt(GiaBan, rowChoice, 4);
                    model.setValueAt(NamSX, rowChoice, 5);
                    model.setValueAt(SoLuong, rowChoice, 6);
                    model.setValueAt(Xilanh, rowChoice, 7);
                    model.setValueAt(Mausac, rowChoice, 8);

                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(this, "Fail");
                }
                isFlag = "";
                KhoaMo(false);
            }
        }
            
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        isFlag = "update";
        KhoaMo(true);
        txtMaSP.setEditable(false);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            ConnectDB.getInstance().connect();
        } catch (Exception e) {
                // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        boolean b= true;
        txtMaSP.setEditable(b);
        txtTenSp.setEditable(b);
        txtNamSX.setEditable(b);
        txtGiaBan.setEditable(b);
        txtSoLuong.setEditable(b);
        cb_LoaiXe.setEnabled(b);
        cbNhaCC.setEnabled(b);
        cbMauSac.setEnabled(b);
        cbXiLanh.setEnabled(b);

        btnThem.setEnabled(b);
        btnSua.setEnabled(b);
        btnXoa.setEnabled(b);

        btnLuu.setEnabled(!b);
        btnHuy.setEnabled(!b);
        
        
        sp_DAO = new SanPham_DAO();
        
        if (tblSanPham.getSelectedRow() >= 0) {
            int row = tblSanPham.getSelectedRow();
            String ma = txtMaSP.getText();
            SanPham sp = new SanPham(ma);
            try {
                sp_DAO.delete(sp);
                DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
                model.removeRow(row);
            } catch (Exception e1) {
                    JOptionPane.showMessageDialog(this, "Not delete");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xóa.");
        }
        xoatrang();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        KhoaMo(false);
        txtMaSP.setEnabled(true);
        xoatrang();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        if (txt_timkiem.getText().equals("")) {
            LayNguonSP();
        }
        try {
            ConnectDB.getInstance().connect();
            String timkiem = txt_timkiem.getText();
            DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
            model.setRowCount(0);
            sp_DAO = new SanPham_DAO();
            ArrayList<SanPham> listSP = sp_DAO.getSanPhamTheoMa(timkiem);
            if (model.getColumnCount() == 0) {
               String[] arr = {"Mã SP", "Tên SP", "Loại Xe", "Nhà CC", "Giá Bán", "Năm SX", "Số Lượng" ,"Xi lanh", "Màu Sắc"};
                model.setColumnIdentifiers(arr);
            }
            for(SanPham sp: listSP) {
                model.addRow(new Object[] { sp.getMaSanPham(),
                                sp.getTenXe(), sp.getMaLoai().getMaLoai(),
                                sp.getNhaPhanPhoi().getMaNhaPhanPhoi(), sp.getNamSanXuat() , sp.getGia(), sp.getSoLuong(),
                                sp.getXiLanh(),sp.getMauSac()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_HienAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HienAllActionPerformed
        //Load lại toàn bộ dữ liệu
        LayNguonSP();
    }//GEN-LAST:event_btn_HienAllActionPerformed

    private void cbNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhaCCActionPerformed
        
    }//GEN-LAST:event_cbNhaCCActionPerformed

    private void cb_LoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_LoaiXeActionPerformed
        
    }//GEN-LAST:event_cb_LoaiXeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_HienAll;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cbMauSac;
    private javax.swing.JComboBox<String> cbNhaCC;
    private javax.swing.JComboBox<String> cbXiLanh;
    private javax.swing.JComboBox<String> cb_LoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNamSX;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSp;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
