/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import connectDB.ConnectDB;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import dao.NhanVien_DAO;
import dao.SanPham_DAO;
import entity.HoaDon;
import entity.KhachHang;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frmStatistics extends javax.swing.JPanel {

    /**
     * Creates new form frmStatistics
     */
    private KhachHang_DAO kh_DAO;
    private HoaDon_DAO hd_DAO;
    private NhanVien_DAO nv_DAO;
    private SanPham_DAO sp_DAO;
    public frmStatistics() {
        initComponents();
        LayNguonSP();
    }
    private void LayNguonSP() {
        tbl_KH.removeAll();
        try {
            ConnectDB.getInstance().connect();
        } catch (Exception e) {
                // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        kh_DAO = new KhachHang_DAO();
        hd_DAO = new HoaDon_DAO();
        nv_DAO = new NhanVien_DAO();
        sp_DAO = new SanPham_DAO();
        
        
//        List<HoaDon> listHD = hd_DAO.getAllTableHoaDon();
        
//        if (tbl_KH.getModel() == null) {
        String[] arr = {"Mã NV", "Mã KH", "Tên KH","Ten SP","Ngày", "Giá"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        tbl_KH.setModel(model);
//        }
//        
//        DefaultTableModel model = (DefaultTableModel) tbl_KH.getModel();
//        model.setRowCount(0);
        
        
        LocalDate ngayHienTai = LocalDate.now();
        
        frmEmployeeHome eh = new frmEmployeeHome();
        
        eh.addToHome2();
        
//        List<frmEmployeeHome.Product> retrievedProducts = eh.getProductsList();
//        for (frmEmployeeHome.Product product : retrievedProducts) {
//            model.addRow(new Object[] {"NV01",
//                "KH0211", "Bình" ,product.getName(), 
//                ngayHienTai, product.getPrice()
//                });
//        }
        model.addRow(new Object[] {"NV01",
            "KH0211", "Bình" ,"XE YAMAHA", 
            ngayHienTai, "20000000"
        });
        model.addRow(new Object[] {"NV01",
            "KH0212", "Dat" ,"XE YAMAHA", 
            ngayHienTai, "20000000"
        });
        model.addRow(new Object[] {"NV01",
            "KH0213", "Tuan" ,"XE YAMAHA", 
            ngayHienTai, "20000000"
        });
        model.addRow(new Object[] {"NV01",
            "KH0214", "Dat" ,"XE YAMAHA", 
            ngayHienTai, "123123123"
        });
        model.addRow(new Object[] {"NV01",
            "KH0215", "Tuan" ,"XE YAMAHA", 
            ngayHienTai, "1241224"
        });
        model.addRow(new Object[] {"NV01",
            "KH0215", "Bình" ,"XE YAMAHA", 
            ngayHienTai, "124"
        });
        model.addRow(new Object[] {"NV01",
            "KH0216", "Bình" ,"XE YAMAHA", 
            ngayHienTai, "123121222"
        });
        model.addRow(new Object[] {"NV01",
            "KH0217", "Bình" ,"XE YAMAHA", 
            ngayHienTai, "12312312312"
        });
        model.addRow(new Object[] {"NV01",
            "KH0218", "Bình" ,"Yamaha Exciter 150", 
            ngayHienTai, "45000000"
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_KH = new javax.swing.JTable();

        tbl_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Mã KH", "Tên KH", "Tên SP", "Ngày", "Giá SP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_KH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_KH;
    // End of variables declaration//GEN-END:variables
}
